/* Automated test driver for Lab 06. DO NOT EDIT THIS FILE. */
public class Lab06PatternsAndPrimesTest {

    public static void main(String[] args) {

        String out1 = TestRunner.runMain(Lab06PatternsAndPrimes::main, "5\n20\n");
        TestRunner.section("Case 1 - 5 rows, primes up to 20");
        TestRunner.checkOutputContains("Triangle header printed", out1, "Triangle:");
        TestRunner.checkTrue("Row 1 is a single asterisk", hasLine(out1, "*"));
        TestRunner.checkTrue("Row 3 has three asterisks", hasLine(out1, "***"));
        TestRunner.checkTrue("Row 5 has five asterisks", hasLine(out1, "*****"));
        TestRunner.checkFalse("No row has six asterisks", hasLine(out1, "******"));
        TestRunner.checkOutputContains("Prime list up to 20", out1, "2 3 5 7 11 13 17 19");
        TestRunner.checkOutputContains("Prime count", out1, "Prime count: 8");

        String out2 = TestRunner.runMain(Lab06PatternsAndPrimes::main, "3\n2\n");
        TestRunner.section("Case 2 - 3 rows, limit 2 (smallest prime)");
        TestRunner.checkTrue("Row 3 has three asterisks", hasLine(out2, "***"));
        TestRunner.checkFalse("No fourth row", hasLine(out2, "****"));
        TestRunner.checkOutputContains("2 is prime", out2, "Prime count: 1");

        String out3 = TestRunner.runMain(Lab06PatternsAndPrimes::main, "1\n1\n");
        TestRunner.section("Case 3 - edge case: 1 row, limit 1 (no primes exist)");
        TestRunner.checkTrue("Row 1 is a single asterisk", hasLine(out3, "*"));
        TestRunner.checkFalse("No second row", hasLine(out3, "**"));
        TestRunner.checkOutputContains("1 is not prime", out3, "Prime count: 0");

        String out4 = TestRunner.runMain(Lab06PatternsAndPrimes::main, "2\n50\n");
        TestRunner.section("Case 4 - primes up to 50");
        TestRunner.checkOutputContains("Prime list up to 50", out4,
                "2 3 5 7 11 13 17 19 23 29 31 37 41 43 47");
        TestRunner.checkOutputContains("Prime count", out4, "Prime count: 15");

        TestRunner.exitWithSummary();
    }

    /** True when some line of the output, ignoring surrounding spaces, equals the target exactly. */
    private static boolean hasLine(String output, String target) {
        for (String line : String.valueOf(output).split("\\R")) {
            if (line.trim().equals(target)) {
                return true;
            }
        }
        return false;
    }
}
